### ISSUE TITLE
SCRUM-83: Optional Google OAuth Sign in 

### ISSUE THREAD

**Issue by XThomasBU** [edubotics-ai/edubotics-core#41]
Give users the option to skip logging in through Google Oauth, and use the chatbot as a guest

We still want to log the interactions for evaluations in chat history, but we can log all these under a generic 'guest' user ID.

**Comment by Farid-Karimli** [comment]
The most direct way as far as I understand is building a [custom frontend](https://github.com/Chainlit/cookbook/tree/main/custom-frontend) using React. It's not gonna be hard, just a good amount of work.

**Comment by XThomasBU** [comment]
Can assign guest access through the FastAPI app -- skips google Oauth
