### ISSUE TITLE
Regenerating credits to cap paid API usage

### ISSUE THREAD

**Issue by trgardos** [edubotics-ai/edubotics-core#6]
When using paid APIs, will need to control for API usage. One way to do this is:

1. Have some kind of user registration based on email and confirmation of emails. (See #9 )
2. Track usage to limit API calls over some period of time.. e.g. 24 hours, 72 hours, or something similar. Have the credit regenerate of that window of time.
3. Indicate the user credits remaining in the UI
4. Optionally, allow users to provide their own API key for unlimited usage.

**Comment by trgardos** [comment]
Code might currently require adding your own API keys. I think we can add one of our own OpenAI keys and cap the spend on the account settings.

**Comment by trgardos** [comment]
Still to be done. Should be able to track the token count through API calls, but then will need to add the UI to display to the user.

**Comment by XThomasBU** [comment]
Added capability in apps/ai_tutor
